services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8081:8000"  # Map container port 8000 (FastAPI) to host port 8081
    volumes:
      - ./api:/app
    environment:
      - ENV=production

  gradio:
    build:
      context: ./gradio
      dockerfile: Dockerfile
    ports:
      - "8082:7860"  # Map container port 7860 (Gradio default) to host port 8082
    volumes:
      - ./gradio:/app
    environment:
      - ENV=production
